### ISSUE TITLE
Rotate() results in panic on some images

### ISSUE THREAD

**Issue by cheston97** [anthonynsimon/bild#60] opened 2018-08-14 18:44 UTC
I've encountered some images for which the Rotate() function results in:
`runtime error: slice bounds out of range`

The error seems to be happening on rotate.go:111:
`copy(dst.Pix[dstPos:dstPos+4], src.Pix[srcPos:srcPos+4])`

An image that can reproduce the error: https://static.thumbtackstatic.com/pictures/61/41zcu25h98b0rquu.jpg

FWIW, opening that image in an editor (e.g. Preview on mac) and simply re-saving it seems to resolve the issue. Unsure what to make of that.

Please let me know if I can provide any more info!

**Comment by Liberatys** [comment] 2019-04-27 08:55
I would like to look into this, if its okay ?

**Comment by Liberatys** [comment] 2019-04-27 09:19
Short follow up, are there any other images that seem not to work ? Because given image: https://static.thumbtackstatic.com/pictures/61/41zcu25h98b0rquu.jpg works just fine on my mac.

**Comment by cheston97** [comment] 2019-04-29 16:37
Sorry, I don't have any others available, and we migrated our image manipulation to another library, so I don't have an easy way to try to repro. Sorry!

**Comment by anthonynsimon** [comment] 2019-04-29 19:59
No worries :)

I guess we can close the issue for now, at least until we can find a case that reproduces it.

**Closed by anthonynsimon** 2019-04-29 19:59 UTC
Labels: bug, help wanted
